cp bo_f.txt bo_fSS.txt
cp bo_pa_f.txt bo_pa_fSS.txt
cp bnh4_f.txt bnh4_fSS.txt
cp bno2_f.txt bno2_fSS.txt
cp d_f.txt d_fSS.txt
cp dom_f.txt dom_fSS.txt
cp nh4_f.txt nh4_fSS.txt
cp no2_f.txt no2_fSS.txt
cp no3_f.txt no3_fSS.txt
cp o_f.txt o_fSS.txt
cp p1_f.txt p1_fSS.txt
cp p2_f.txt p2_fSS.txt
cp p3_f.txt p3_fSS.txt
cp xp1_f.txt xp1_fSS.txt
cp xp2_f.txt xp2_fSS.txt
cp xp3_f.txt xp3_fSS.txt
cp zoo_f.txt zoo_fSS.txt
cp zoo2_f.txt zoo2_fSS.txt
cp zoo3_f.txt zoo3_fSS.txt
